### ISSUE TITLE
Item "agent.hostname" already exists on , inherited from another template.

### ISSUE THREAD

**Issue by lakinmohapatra** [soliantconsulting/FileMaker-Server-Zabbix-Templates#2]
I am getting this error while linking solitan template "Soliant FMS FMC" 

"Item "agent.hostname" already exists on , inherited from another template."

Please advise.

**Comment by mislavkos** [comment]
Hello, 

Zabbix doesn't allow you to create duplicate items in a template or for a host. An item key uniquely identifies an item, so you can't define multiple items that use the same key.

With our Soliant templates, we defined an item with the "agent.hostname" item key in our "Soliant FMS WinMacFMC" template, which is inherited by the "Soliant FMS FMC" template. That item key is not used anywhere else in our templates.

Have you linked other templates to your host, and does one of those other templates have an item defined with that same "agent.hostname" item key? If so, then that would be the cause of the problem. To resolve this, you can remove that item from that template or from the "Soliant FMS FMC" template.
