### ISSUE TITLE
FMS admin api config Unsupported Item Key

### ISSUE THREAD

**Issue by marcoaperez** [soliantconsulting/FileMaker-Server-Zabbix-Templates#4]
I have Zabbix 5.0.2 installed and the FMS Admin API config won't work. It says unsupported item key.

When I run the text I get nothing, except that.

The Zabbix Agent es 5 too. Everything else seems to work, except all dependencies of this item.

I have enabled AllowKey=system.run[*]

But I don't know anything else to do. I don't really understand this.

thanks for the help

**Comment by marcoaperez** [comment]
#
<img width="822" alt="Screenshot 2020-10-12 at 16 29 13" src="https://user-images.githubusercontent.com/25101951/95758418-bffd0000-0ca8-11eb-9f35-83d1343f5398.png">

**Comment by marcoaperez** [comment]
After reviewing your article, I figure maybe it wasn't the allow key, but the permissions, because I didn't have a zabbix user created when a installed the agent, so I introduced a 777 permission in the fms_config.py and it works but I don't want to leave that kind of permission

**Comment by wimdecorte** [comment]
Locking down the deployment will vary by deployment and the risk appetite.  Consider the options for your OS on how to run the agent, with what level of permissions.
