### ISSUE TITLE
"ps" command on Mac may truncate results

### ISSUE THREAD

**Issue by jedtech-john** [soliantconsulting/FileMaker-Server-Zabbix-Templates#5]
The terminal command "ps -u fmserver ..." is being used to track which fmserver processes are alive.  On Mac the command only outputs 80 character lines so depending on the path to the FileMaker Server folder the result may be truncated.  For example on a machine with "Macintosh HD" as the boot drive and FileMaker Server installed in the standard location the relevant line of the ouput is:

S    /Volumes/Macintosh HD/Library/FileMaker Server/Database Server/bin/fmserve

by adding the "-w" flag to the command so "ps -u fmserver -w ..." it increases the output width to 132 columns which in most cases will solve the problem.  Using the "-ww" flag will give unlimited width.

**Comment by wimdecorte** [comment]
Thanks, I'll check if it has any effect on the parsing and make the change.

**Comment by wimdecorte** [comment]
Incorporated in next release, for macOS template only.  Same item for Linux doesn't need it.
