### ISSUE TITLE
fmserverd on Mac can fail during backup

### ISSUE THREAD

**Issue by jedtech-john** [soliantconsulting/FileMaker-Server-Zabbix-Templates#8]
The "FMS Process Database Engine" item sometimes reports down when it is actually running a backup.  The query for "All FMS Processes" of

     system.run["ps -u fmserver -ww -o state,comm",wait]

returns the first character of the fmserverd process line as a "U" indicating it is in an "uninterruptable wait".

The preprocessing JavaScript looks for:

    var pattern = "\n([D,R,S]).*fmserverd";

According to the ps man page in macOS Catalina the valid values of the first character are:

  I       Marks a process that is idle (sleeping for longer than about 20 seconds).
  R       Marks a runnable process.
  S       Marks a process that is sleeping for less than about 20 seconds.
  T       Marks a stopped process.
  U       Marks a process in uninterruptible wait.
  Z       Marks a dead process (a ``zombie'').

to allow a "U" line to indicate that fmserverd is still running the script line could be changed to:

    var pattern = "\n([U,R,S]).*fmserverd";

**Comment by jedtech-john** [comment]
The same issue also applies to "FMS Process Scripting Engine" (fmsased), "FMS Process CWP" (fmscwpc), "FMS Process Wrapper" (fmserver_helperd), "FMS Process Progressive Backups" (fmsib), and "FMS Process Data API" (fmwipd)

**Comment by wimdecorte** [comment]
The original has D to cover the uninterruptible wait; I'll modify the macOS template to use U, and the Linux one to keep using D

**Comment by wimdecorte** [comment]
verified that Big Sur still uses U, Ubuntu uses D

**Comment by wimdecorte** [comment]
fixed in our working copy, will be in the next release
