### ISSUE TITLE
"Machintosh HD" typo in soliant_fms_zbx_export_templates.xml

### ISSUE THREAD

**Issue by jedtech-john** [soliantconsulting/FileMaker-Server-Zabbix-Templates#9]
In soliant_fms_zbx_export_templates.xml the default value for macro $FM_DATABASE_VOLUME for Mac is at line 2988 is "Machintosh HD" and should be "Macintosh HD".

**Comment by wimdecorte** [comment]
Will be fixed in the next release, thanks!
